In [1]:
import torch

In [12]:
inputs = torch.tensor([
    [0.33,0.15,0.86],
    [0.12,0.13,0.31],
    [0.31,0.61,0.18],
    [0.11,0.31,0.11],
    [0.51,0.22,0.41],
    [0.13,0.85,0.24]
])

In [17]:
query = inputs[1]

attn_scores_2 = torch.empty(inputs.shape[0])

for i ,x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i,query)
attn_scores_2

tensor([0.3257, 0.1274, 0.1723, 0.0876, 0.2169, 0.2005])

In [21]:
attn_weights_2_temp = attn_scores_2/ attn_scores_2.sum()
attn_weights_2_temp.sum()

tensor(1.)

In [26]:
attn_weights_2_temp,attn_scores_2

(tensor([0.2881, 0.1127, 0.1524, 0.0775, 0.1919, 0.1774]),
 tensor([0.3257, 0.1274, 0.1723, 0.0876, 0.2169, 0.2005]))

In [27]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_scores_2)
attn_weights_2_naive

tensor([0.1906, 0.1564, 0.1635, 0.1503, 0.1710, 0.1682])

In [28]:
attn_weights_2_naive.sum()

tensor(1.)

In [31]:
attn_weights_2= torch.softmax(attn_scores_2,dim=0)

In [34]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)

for i , x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] * x_i
context_vec_2

tensor([0.2580, 0.3759, 0.3689])

In [35]:
inputs

tensor([[0.3300, 0.1500, 0.8600],
        [0.1200, 0.1300, 0.3100],
        [0.3100, 0.6100, 0.1800],
        [0.1100, 0.3100, 0.1100],
        [0.5100, 0.2200, 0.4100],
        [0.1300, 0.8500, 0.2400]])

In [43]:
attn_scores = torch.empty(6,6)

for j,j_x in enumerate(inputs):
    for i,i_x in enumerate(inputs):
        attn_scores[i,j] = torch.dot(i_x,j_x)
    
attn_scores

tensor([[0.8710, 0.3257, 0.3486, 0.1774, 0.5539, 0.3768],
        [0.3257, 0.1274, 0.1723, 0.0876, 0.2169, 0.2005],
        [0.3486, 0.1723, 0.5006, 0.2430, 0.3661, 0.6020],
        [0.1774, 0.0876, 0.2430, 0.1203, 0.1694, 0.3042],
        [0.5539, 0.2169, 0.3661, 0.1694, 0.4766, 0.3517],
        [0.3768, 0.2005, 0.6020, 0.3042, 0.3517, 0.7970]])

In [44]:
attn_scores = inputs @ inputs.T
attn_scores

tensor([[0.8710, 0.3257, 0.3486, 0.1774, 0.5539, 0.3768],
        [0.3257, 0.1274, 0.1723, 0.0876, 0.2169, 0.2005],
        [0.3486, 0.1723, 0.5006, 0.2430, 0.3661, 0.6020],
        [0.1774, 0.0876, 0.2430, 0.1203, 0.1694, 0.3042],
        [0.5539, 0.2169, 0.3661, 0.1694, 0.4766, 0.3517],
        [0.3768, 0.2005, 0.6020, 0.3042, 0.3517, 0.7970]])

In [47]:
attn_weights = torch.softmax(attn_scores,dim=1)
attn_weights

tensor([[0.2493, 0.1445, 0.1479, 0.1246, 0.1816, 0.1521],
        [0.1906, 0.1564, 0.1635, 0.1503, 0.1710, 0.1682],
        [0.1611, 0.1350, 0.1875, 0.1449, 0.1639, 0.2075],
        [0.1652, 0.1510, 0.1764, 0.1560, 0.1639, 0.1875],
        [0.2014, 0.1438, 0.1669, 0.1371, 0.1864, 0.1645],
        [0.1534, 0.1286, 0.1922, 0.1427, 0.1496, 0.2335]])

In [49]:
all_context_vector = attn_weights @ inputs
all_context_vector

tensor([[0.2715, 0.3542, 0.4105],
        [0.2580, 0.3759, 0.3689],
        [0.2540, 0.4135, 0.3471],
        [0.2524, 0.3958, 0.3500],
        [0.2670, 0.3740, 0.3788],
        [0.2480, 0.4326, 0.3395]])

In [50]:
context_vec_2

tensor([0.2580, 0.3759, 0.3689])

In [52]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [53]:
torch.manual_seed(36)
W_query = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)

In [54]:
query_2 =  x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2)

tensor([0.2965, 0.1616])


In [55]:
keys = inputs @ W_key
values = inputs @ W_value
keys,values

(tensor([[1.1632, 1.1382],
         [0.4719, 0.4382],
         [0.7964, 0.6699],
         [0.3919, 0.3125],
         [0.8862, 0.9266],
         [0.9021, 0.6401]]),
 tensor([[0.4902, 0.1993],
         [0.2035, 0.0960],
         [0.4837, 0.2322],
         [0.2138, 0.1197],
         [0.5521, 0.1523],
         [0.4425, 0.3130]]))

In [56]:
keys_2 = keys[1]

In [57]:
attn_scores_22 = query_2.dot(key_2)
print(attn_scores_22)

tensor(0.2107)


In [58]:
attn_scores_2 = query_2 @ keys.T
attn_scores_2

tensor([0.5288, 0.2107, 0.3444, 0.1667, 0.4125, 0.3709])

In [60]:
d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2/d_k**0.5,dim=-1)
attn_weights_2

tensor([0.1899, 0.1517, 0.1667, 0.1470, 0.1749, 0.1698])

In [62]:
context_vec = attn_weights_2 @ values
context_vec

tensor([0.4077, 0.1885])

In [84]:
import torch.nn as nn

class SelfAttention_V1(nn.Module):
    def __init__(self,d_in,d_out):
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out
        self.W_query = nn.Parameter(torch.rand(self.d_in,self.d_out))
        self.W_key = nn.Parameter(torch.rand(self.d_in,self.d_out))
        self.W_value = nn.Parameter(torch.rand(self.d_in,self.d_out))
    
    def forward(self,x):
        keys = x @ self.W_key
        queries = x @ self.W_query
        values = x @ self.W_value
        attn_scores = queries @ keys.T 
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5,dim=-1)
        context_vec = attn_weights @ values
        
        return context_vec

In [85]:
torch.manual_seed(36)
sa_V1 = SelfAttention_V1(d_in,d_out)
sa_V1(inputs)

tensor([[0.4222, 0.1929],
        [0.4077, 0.1885],
        [0.4145, 0.1897],
        [0.4057, 0.1875],
        [0.4183, 0.1914],
        [0.4148, 0.1896]], grad_fn=<MmBackward0>)

In [72]:
context_vec

tensor([0.4077, 0.1885])

In [88]:
class SelfAttention_V2(nn.Module):
    def __init__(self,d_in,d_out,bias=False):
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out
        self.w_query = nn.Linear(self.d_in,self.d_out,bias=bias)
        self.w_key = nn.Linear(self.d_in,self.d_out,bias=bias)
        self.w_value = nn.Linear(self.d_in,self.d_out,bias=bias)
        
    def forward(self,x):
        queries = self.w_query(x)
        keys = self.w_key(x)
        values = self.w_value(x)
        
        attn_score = queries @ keys.T
        attn_weights = torch.softmax(attn_score/keys.shape[-1]**0.5,dim=1)
        context_vec = attn_weights @ values
        return context_vec

In [89]:
torch.manual_seed(36)
sa_V2 = SelfAttention_V2(d_in,d_out)
sa_V2(inputs)

tensor([[-0.1864, -0.3061],
        [-0.1917, -0.3099],
        [-0.1943, -0.3117],
        [-0.1942, -0.3116],
        [-0.1910, -0.3094],
        [-0.1943, -0.3117]], grad_fn=<MmBackward0>)

In [90]:
queries = sa_V2.w_query(inputs)
keys = sa_V2.w_key(inputs)
attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5,dim=1)
print(attn_weights)

tensor([[0.1625, 0.1810, 0.1596, 0.1777, 0.1715, 0.1476],
        [0.1655, 0.1715, 0.1642, 0.1704, 0.1682, 0.1601],
        [0.1678, 0.1676, 0.1656, 0.1669, 0.1657, 0.1663],
        [0.1671, 0.1675, 0.1660, 0.1671, 0.1663, 0.1660],
        [0.1653, 0.1729, 0.1635, 0.1714, 0.1685, 0.1584],
        [0.1683, 0.1679, 0.1653, 0.1670, 0.1653, 0.1664]],
       grad_fn=<SoftmaxBackward0>)


In [104]:
attn_scores

tensor([[-2.8939e-01, -1.3656e-01, -3.1452e-01, -1.6278e-01, -2.1338e-01,
         -4.2494e-01],
        [-9.6433e-02, -4.5649e-02, -1.0722e-01, -5.5150e-02, -7.3396e-02,
         -1.4326e-01],
        [ 5.5032e-04, -8.3603e-04, -1.8121e-02, -6.7263e-03, -1.7345e-02,
         -1.2046e-02],
        [-6.5399e-03, -3.6328e-03, -1.6447e-02, -7.1887e-03, -1.3678e-02,
         -1.6016e-02],
        [-1.2094e-01, -5.7377e-02, -1.3663e-01, -6.9977e-02, -9.4091e-02,
         -1.8115e-01],
        [ 3.2356e-03,  1.9355e-05, -2.2239e-02, -7.8603e-03, -2.2037e-02,
         -1.2933e-02]], grad_fn=<MmBackward0>)

In [95]:
block_size = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(block_size,block_size))
mask_simple

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [96]:
masked_simple = attn_weights* mask_simple
masked_simple

tensor([[0.1625, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1655, 0.1715, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1678, 0.1676, 0.1656, 0.0000, 0.0000, 0.0000],
        [0.1671, 0.1675, 0.1660, 0.1671, 0.0000, 0.0000],
        [0.1653, 0.1729, 0.1635, 0.1714, 0.1685, 0.0000],
        [0.1683, 0.1679, 0.1653, 0.1670, 0.1653, 0.1664]],
       grad_fn=<MulBackward0>)

In [100]:
row_sum = masked_simple.sum(dim=1,keepdim=True)
masked_simple_norm = masked_simple/row_sum
masked_simple_norm

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4910, 0.5090, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3349, 0.3346, 0.3305, 0.0000, 0.0000, 0.0000],
        [0.2503, 0.2509, 0.2486, 0.2502, 0.0000, 0.0000],
        [0.1964, 0.2055, 0.1943, 0.2036, 0.2002, 0.0000],
        [0.1683, 0.1679, 0.1653, 0.1670, 0.1653, 0.1664]],
       grad_fn=<DivBackward0>)

In [111]:
mask = torch.triu(torch.ones(block_size,block_size),diagonal=1)
masked = attn_scores.masked_fill(mask.bool(),-torch.inf)
print(masked)

tensor([[-2.8939e-01,        -inf,        -inf,        -inf,        -inf,
                -inf],
        [-9.6433e-02, -4.5649e-02,        -inf,        -inf,        -inf,
                -inf],
        [ 5.5032e-04, -8.3603e-04, -1.8121e-02,        -inf,        -inf,
                -inf],
        [-6.5399e-03, -3.6328e-03, -1.6447e-02, -7.1887e-03,        -inf,
                -inf],
        [-1.2094e-01, -5.7377e-02, -1.3663e-01, -6.9977e-02, -9.4091e-02,
                -inf],
        [ 3.2356e-03,  1.9355e-05, -2.2239e-02, -7.8603e-03, -2.2037e-02,
         -1.2933e-02]], grad_fn=<MaskedFillBackward0>)


In [112]:
attn_weights = torch.softmax(masked/keys.shape[-1] **0.5,dim=1)
attn_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4910, 0.5090, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3349, 0.3346, 0.3305, 0.0000, 0.0000, 0.0000],
        [0.2503, 0.2509, 0.2486, 0.2502, 0.0000, 0.0000],
        [0.1964, 0.2055, 0.1943, 0.2036, 0.2002, 0.0000],
        [0.1683, 0.1679, 0.1653, 0.1670, 0.1653, 0.1664]],
       grad_fn=<SoftmaxBackward0>)

In [114]:
context_vec = attn_weights @ values
context_vec

tensor([[0.4902, 0.1993],
        [0.3443, 0.1467],
        [0.3921, 0.1756],
        [0.3475, 0.1616],
        [0.3861, 0.1588],
        [0.3971, 0.1852]], grad_fn=<MmBackward0>)

In [116]:
torch.manual_seed(36)
dropout = torch.nn.Dropout(0.5)
example = torch.ones(6,6)
dropout(example)

tensor([[2., 2., 0., 2., 2., 0.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 0., 2., 0., 2.],
        [2., 0., 2., 0., 0., 2.],
        [2., 2., 2., 0., 2., 0.],
        [0., 2., 0., 2., 0., 0.]])

In [117]:
dropout(attn_weights)

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.9820, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6692, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5017, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3929, 0.0000, 0.3885, 0.0000, 0.4004, 0.0000],
        [0.3365, 0.3358, 0.3305, 0.3339, 0.3306, 0.3327]],
       grad_fn=<MulBackward0>)